# Generated by Django 5.0.3 on 2024-03-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('seccion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaIngreso', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('curso', models.OneToOneField(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, to='colegio.curso')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='colegio.usuario'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pc1', models.FloatField()),
                ('pc2', models.FloatField()),
                ('pc3', models.FloatField()),
                ('examenFinal', models.FloatField()),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, to='colegio.curso')),
                ('usuario', models.ForeignKey(db_column='calificaciones_usuarios', on_delete=django.db.models.deletion.RESTRICT, to='colegio.usuario')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
    ]
